sinaq ders 1/Controllers/FeatureController.cs
using BusinessLayer.Concrate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrate;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sinaq_ders_1.Controllers
{
    public class FeatureController : Controller
    {
        FeatureManager featureManager = new FeatureManager(new EfFeatureDal());
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.v1 = "Duzenleme";
            ViewBag.v2 = "One cixanlar";
            ViewBag.v3 = "One cixan sehifesi";
            var values = featureManager.TGetByID(1);
            return View(values);
        }
        [HttpPost]
        public IActionResult Index(Feature feature)
        {
            featureManager.TUpdate(feature);
            return RedirectToAction("Index","Default");
        }
    }
}

sinaq ders 1/Views/Feature/Index.cshtml
@model EntityLayer.Concrate.Feature
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("Index", "Feature", FormMethod.Post))
{
    @Html.HiddenFor(x => x.FeatureID)
    <br />
    <br />
    @Html.Label("Header")
    @Html.TextBoxFor(x => x.Header, new { @class = "form-control" })
    <br />
    @Html.Label("Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.Label("Title")
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
  
    <button class="btn btn-success">Guncelle</button>

}