sinaq ders 1/Controllers/SkillController.cs
using BusinessLayer.Concrate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrate;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sinaq_ders_1.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkillDal());
        public IActionResult Index()
        {
            ViewBag.V1 = "Bacariqlar Səhifəsi";
            ViewBag.V2 = "Bacariqlar";
            ViewBag.V3 = "Bacariqlar Səhifəsi";
            var values = skillManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.V1 = "Bacariqlar Yükləmə";
            ViewBag.V2 = "Bacariqlar";
            ViewBag.V3 = "Bacariqlar Yükləmə";
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill Skill)
        {
            skillManager.TAdd(Skill);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetByID(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.V1 = "Bacariqlar Guncelleme";
            ViewBag.V2 = "Bacariqlar";
            ViewBag.V3 = "Bacariqlar Guncelleme";
            var values = skillManager.TGetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }

    }
}

sinaq ders 1/Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrate.Skill
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description"> Yeni Yetenek Ekleme </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>Baslik</label>
                    @Html.TextBoxFor(x=>x.Title , new { @class="form-control"})
                </div>
                <div class="form-group">
                    <label>Deyer</label>
                    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                </div>

                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button class="btn btn-dark">Iptal</button>
            </form>
        </div>
    </div>
</div>

sinaq ders 1/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrate.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Bacariqlar Guncellem Səhifəsi</h3>
</div>

@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Duzenleme Sehifesi </p>
                <form class="forms-sample" >
                    @Html.HiddenFor(x=>x.SkillID)
                    <div class="form-group">
                        <label>Baslik</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Deyer</label>
                        @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">Iptal</button>
                </form>
            </div>
        </div>
    </div>

}

sinaq ders 1/Views/Skill/Index.cshtml
@using EntityLayer.Concrate
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}



<div class="card-header border-0">
    <h3 class="mb-0">Bacariqlar Cedveli</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlıq</th>
                <th scope="col" class="sort" data-sort="status">Value</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Düzənlə</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.SkillID
                    </th>
                    <td class="budget">
                        @item.Title
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <span class="completion mr-2">@item.Value%</span>
                            <div>
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-info">Güncəllə</a></td>
                </tr>
            }

        </tbody>
    </table>
    <a href="/Skill/AddSkill/" class="btn btn-primary">Yeni Bacarıq Yüklə</a>
</div>

<script src="~/blacktemplate/assets//vendors/js/vendor.bundle.base.js"></script>